export default {
  login: 'fajarmarif22',
  id: 97581196,
  node_id: 'U_kgDOBdD4jA',
  avatar_url: 'https://avatars.githubusercontent.com/u/97581196?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/fajarmarif22',
  html_url: 'https://github.com/fajarmarif22',
  followers_url: 'https://api.github.com/users/fajarmarif22/followers',
  following_url:
    'https://api.github.com/users/fajarmarif22/following{/other_user}',
  gists_url: 'https://api.github.com/users/fajarmarif22/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/fajarmarif22/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/fajarmarif22/subscriptions',
  organizations_url: 'https://api.github.com/users/fajarmarif22/orgs',
  repos_url: 'https://api.github.com/users/fajarmarif22/repos',
  events_url: 'https://api.github.com/users/fajarmarif22/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/fajarmarif22/received_events',
  type: 'User',
  site_admin: false,
  name: 'Fajar Maulana Arif',
  company: null,
  blog: '',
  location: 'Bandung',
  email: null,
  hireable: null,
  bio: 'Front-end Dev.',
  twitter_username: null,
  public_repos: 26,
  public_gists: 0,
  followers: 1,
  following: 2,
  created_at: '2022-01-12T05:11:03Z',
  updated_at: '2022-12-14T04:46:27Z',
}
